### ISSUE TITLE
Make "fn max_size() -> usize" to be an associated constant

### ISSUE THREAD

**Issue by kvark** [djg/peek-poke#6]
```rust
const MAX_SIZE: usize;
```
This would make it a stronger guarantee that the function returns consistent result, at least.

**Comment by djg** [comment]
If I remember correctly, it was because of a bug in the compiler. For generic types, the compiler couldn't see T::MAX_SIZE.  I just tried with the latest compiler and that doesn't appear to be a problem anymore.

To support returning the largest variant for an enum, we need a const fn version of `max()` because `{core, std}::cmp::max` can't be used in a constant context.

**Comment by djg** [comment]
Ok, I found that I can use:

```
const fn max(a: usize, b: usize) -> usize {
    [a, b][(a < b) as usize]
}
```

to implement a constant max function. I updated the code and all the tests pass with version `1.39` of the stable compiler.
